### ISSUE TITLE
Publishing Usage Data to Stripe Fails

### ISSUE THREAD

**Issue by viggnah** [wso2-extensions/wso2-am-stripe-plugin#40]
**Description:**
When I follow the [monetization documentation](https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/#connectID) at step 4, sub step 3 `Publish usage data to the Stripe billing engine` I get the following error:
```
ERROR {org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent} - Failed to publish monetization usage to billing Engine java.lang.NullPointerException
	at org.wso2.apim.monetization.impl.StripeMonetizationImpl.publishMonetizationUsageRecords(StripeMonetizationImpl.java:681)
	at org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent.run_aroundBody0(MonetizationUsagePublishAgent.java:62)
	at org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent.run(MonetizationUsagePublishAgent.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

1. Note that since the documentation links to the `Release v1.3.1`, I used that jar.
2. However, when I tried with `v1.3.2` and tried to publish usage data I got the following different error:
```
Exception in thread "pool-320-thread-1" java.lang.NoClassDefFoundError: co/elastic/clients/util/ObjectBuilder
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassForName_aroundBody446(APIUtil.java:6592)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassForName(APIUtil.java:6589)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassInstance_aroundBody444(APIUtil.java:6576)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassInstance(APIUtil.java:6573)
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getMonetizationImplClass_aroundBody18(APIAdminImpl.java:269)
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getMonetizationImplClass(APIAdminImpl.java:256)
	at org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent.run_aroundBody0(MonetizationUsagePublishAgent.java:51)
	at org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent.run(MonetizationUsagePublishAgent.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: co.elastic.clients.util.ObjectBuilder cannot be found by org.wso2.apim.monetization.impl_1.3.2_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more
```
3. Then I tried to pull the latest from the repo and build locally and got the following error when repeating the publishing step:
```
Exception in thread "pool-316-thread-1" java.lang.NoClassDefFoundError: co/elastic/clients/json/JsonpMapper
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassForName_aroundBody446(APIUtil.java:6592)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassForName(APIUtil.java:6589)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassInstance_aroundBody444(APIUtil.java:6576)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getClassInstance(APIUtil.java:6573)
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getMonetizationImplClass_aroundBody18(APIAdminImpl.java:269)
	at org.wso2.carbon.apimgt.impl.APIAdminImpl.getMonetizationImplClass(APIAdminImpl.java:256)
	at org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent.run_aroundBody0(MonetizationUsagePublishAgent.java:51)
	at org.wso2.carbon.apimgt.impl.monetization.MonetizationUsagePublishAgent.run(MonetizationUsagePublishAgent.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: co.elastic.clients.json.JsonpMapper cannot be found by org.wso2.apim.monetization.impl_1.3.2_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more
```

**Suggested Labels:**
None

**Suggested Assignees:**
None

**Affected Product Version:**
- WSO2 API Manager v4.1.0
- org.wso2.apim.monetization.impl-1.3.1.jar
- org.wso2.apim.monetization.impl-1.3.2.jar

**OS, DB, other environment details and versions:**   
- macOS 12.2.1
- mysql  Ver 8.0.29 for macos12.2 on arm64 (Homebrew) for WSO2AM_DB
- Default H2 DB for WSO2SHARED_DB

**Steps to reproduce:**
Follow the [monetization documentation](https://apim.docs.wso2.com/en/latest/design/api-monetization/monetizing-an-api/#connectID) and at step 4, sub step 3 `Publish usage data to the Stripe billing engine` you will get the error.

In case this is important: I connected the same platform account as the connected account in Stripe. But everything went as mentioned in the docs including creation of subscription plan, and creation of platform and shared customers on Stripe.

**Related Issues:**
None

**Comment by viggnah** [comment]
I was able to resolve the publishing issue. Basically, the `$onPremKey` is not the JWT generated by the application subscribed to the Insights API but the on-prem key present on the Choreo Console settings page.

I did it with `v1.3.1` jar. I couldn't use the `v1.3.2` jar, since I was getting the error in point `2` above.
